from __future__ import annotations
"""
compliance_doc_generator.py

Generates a HIPAA Technical Safeguards Summary from scan results.
Output is a compliance officer-ready draft Markdown document.
Not a certified compliance audit — a structured starting point.
"""

import sys
import json
import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from state_manager import RawFinding


# HIPAA Technical Safeguard categories with CFR references
_SAFEGUARDS = {
    "access_control": {
        "title": "Access Control (§164.312(a))",
        "rule_ids": ["PHI-001", "PHI-002", "PHI-003", "PHI-005"],
        "description": "Unique user identification, emergency access procedures, automatic logoff, encryption/decryption.",
    },
    "audit_controls": {
        "title": "Audit Controls (§164.312(b))",
        "rule_ids": ["PHI-004", "PHI-006", "AUDIT-001", "AUDIT-002"],
        "description": "Hardware, software, and procedural mechanisms to record and examine activity in systems containing ePHI.",
    },
    "integrity": {
        "title": "Integrity (§164.312(c))",
        "rule_ids": ["ENC-001"],
        "description": "Protect ePHI from improper alteration or destruction.",
    },
    "authentication": {
        "title": "Person or Entity Authentication (§164.312(d))",
        "rule_ids": ["CRED-001", "CRED-002", "CRED-003"],
        "description": "Verify that a person or entity seeking access is who they claim to be.",
    },
    "transmission_security": {
        "title": "Transmission Security (§164.312(e))",
        "rule_ids": ["FHIR-003", "AUDIT-002"],
        "description": "Guard against unauthorized access to ePHI transmitted over electronic networks.",
    },
    "minimum_necessary": {
        "title": "Minimum Necessary (§164.502(b))",
        "rule_ids": ["FHIR-001", "FHIR-002"],
        "description": "Limit PHI access to the minimum necessary to accomplish the intended purpose.",
    },
}


def generate(findings: list[RawFinding], baa_results: dict | None, output_path: str) -> None:
    """Generate and write the compliance report."""
    doc = _build_document(findings, baa_results)
    Path(output_path).write_text(doc, encoding="utf-8")


def _build_document(findings: list[RawFinding], baa_results: dict | None) -> str:
    today = datetime.date.today().isoformat()
    confirmed_by_rule: dict[str, int] = {}
    for f in findings:
        confirmed_by_rule[f.rule_id] = confirmed_by_rule.get(f.rule_id, 0) + 1

    lines = [
        "# HIPAA Technical Safeguards Implementation Summary",
        f"**Generated:** {today}  |  **Tool:** HIPAA-Guard  |  **Status:** DRAFT — Requires compliance officer review",
        "",
        "> This document is an automated draft generated by scanning source code. It identifies",
        "> implemented safeguards and gaps. It is NOT a certified compliance audit.",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
    ]

    total_findings = len(findings)
    critical_high = sum(1 for f in findings if f.severity.value in ("critical", "high"))

    if total_findings == 0:
        lines.append("✅ No HIPAA violations detected in the current codebase scan.")
    else:
        lines += [
            f"- **{total_findings}** potential violations detected",
            f"- **{critical_high}** are CRITICAL or HIGH severity",
            f"- Remediation required before next production deployment.",
        ]

    lines += ["", "---", "", "## Technical Safeguard Status by Category", ""]

    for safeguard_key, safeguard in _SAFEGUARDS.items():
        rule_ids = safeguard["rule_ids"]
        violations_in_category = {r: confirmed_by_rule.get(r, 0) for r in rule_ids}
        total_violations = sum(violations_in_category.values())

        status_icon = "✅" if total_violations == 0 else "⚠️"
        lines += [
            f"### {status_icon} {safeguard['title']}",
            f"*{safeguard['description']}*",
            "",
        ]

        if total_violations == 0:
            lines.append("No violations detected for this safeguard category.")
        else:
            lines.append(f"**{total_violations} violation(s) detected:**")
            lines.append("")
            lines.append("| Rule | Occurrences |")
            lines.append("|------|-------------|")
            for rule_id, count in violations_in_category.items():
                if count > 0:
                    lines.append(f"| {rule_id} | {count} |")

        lines += ["", "**Implementation notes:**", ""]

        if safeguard_key == "access_control":
            lines += [
                "- [ ] Unique user IDs implemented for all system access",
                "- [ ] Automatic session timeout configured",
                "- [ ] PHI access requires authentication",
            ]
        elif safeguard_key == "audit_controls":
            lines += [
                "- [ ] All PHI access events are logged",
                "- [ ] Audit logs are append-only and tamper-evident",
                "- [ ] Log retention policy: minimum 6 years (45 CFR §164.316(b)(2))",
            ]
        elif safeguard_key == "transmission_security":
            lines += [
                "- [ ] All FHIR endpoints use HTTPS (TLS 1.2+)",
                "- [ ] Certificate validity monitored",
                "- [ ] No PHI transmitted over unencrypted channels",
            ]
        elif safeguard_key == "authentication":
            lines += [
                "- [ ] No credentials hardcoded in source code",
                "- [ ] Secrets managed via environment variables or vault",
                "- [ ] All exposed credentials rotated",
            ]
        elif safeguard_key == "minimum_necessary":
            lines += [
                "- [ ] FHIR scopes limited to minimum required resources",
                "- [ ] Scope justification documented per integration",
            ]

        lines.append("")

    # BAA section
    lines += ["---", "", "## Third-Party BAA Status", ""]
    if baa_results:
        lines += [
            f"Dependencies analyzed: **{baa_results['total_dependencies']}**",
            f"PHI-touching packages: **{baa_results['phi_touching']}**",
            f"Requiring BAA investigation: **{baa_results.get('action_required_count', 0)}**",
            "",
        ]
        action_items = [f for f in baa_results.get("findings", []) if f.get("action_required")]
        if action_items:
            lines += ["**Action required — obtain or confirm BAA for:**", ""]
            lines.append("| Package | BAA Status | Notes |")
            lines.append("|---------|-----------|-------|")
            for item in action_items:
                lines.append(f"| `{item['package']}` | {item['baa_status']} | {item['notes'][:60]}... |")
        else:
            lines.append("✅ All PHI-touching packages have confirmed BAA status.")
    else:
        lines.append("BAA check not run. Execute `hipaa-guard baa` to generate BAA inventory.")

    lines += [
        "",
        "---",
        "",
        "## Required Next Steps",
        "",
        "1. **Remediate all CRITICAL and HIGH findings** before next production deployment.",
        "2. **Obtain BAAs** for any third-party services with `UNKNOWN` or `NOT_AVAILABLE` status that touch PHI.",
        "3. **Complete implementation checklist** items above for each safeguard category.",
        "4. **Have this document reviewed** by a qualified HIPAA compliance officer.",
        "5. **Retain this document** for a minimum of 6 years per 45 CFR §164.316(b)(2).",
        "",
        "---",
        "",
        "_HIPAA-Guard is an automated scanning tool. This report identifies code-level compliance gaps._",
        "_It does not constitute legal advice or a certified compliance audit._",
        "_Consult a qualified HIPAA compliance officer before certifying compliance._",
    ]

    return "\n".join(lines)
